on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: choice
        options:
          - test
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
                    
      - name: Setup Python    
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: "pip install -r requirements-dev.txt"
      - name: Build
        run: "python setup.py build_exe -b slicebug-release"
      - name: Zip release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: slicebug-windows.zip
          path: slicebug-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

        with:
          files: slicebug-windows.zip
